name: 'GitHub Secrets'

on: workflow_dispatch

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
        - name: 'Print Secret'
          run: |
            echo "MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}"
        - name: 'Print Secret as an environment variable'
          env: 
            MY_TOP_SECRET: ${{ secrets.MY_TOP_SECRET }}
          run: |
            echo "MY_TOP_SECRET: $MY_TOP_SECRET"
